import time
import json
from datetime import datetime
from io import BytesIO
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from app.core.config import get_settings
from app.workers.celery_app import celery_app
from app.models.report import Report, ReportStatus, ReportType, ReportFormat

settings = get_settings()

sync_engine = create_engine(
    settings.DATABASE_URL.replace("+asyncpg", "+psycopg2"),
    pool_size=5,
    max_overflow=10,
)
SyncSessionLocal = sessionmaker(bind=sync_engine)

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor


def _generate_pdf_content(report: Report, db: Session) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(report.title, styles["Title"]))
    story.append(Spacer(1, 20))

    content = report.content or {}
    for section_key, section_data in content.items():
        title = section_data.get("title", section_key.replace("_", " ").title())
        body = section_data.get("content", "")

        story.append(Paragraph(title, styles["Heading1"]))
        story.append(Spacer(1, 10))

        if isinstance(body, str):
            for paragraph in body.split("\n"):
                if paragraph.strip():
                    story.append(Paragraph(paragraph.strip(), styles["Normal"]))
                    story.append(Spacer(1, 6))
        elif isinstance(body, list):
            items = [ListItem(Paragraph(item, styles["Normal"])) for item in body if item]
            story.append(ListFlowable(items, bulletType="bullet"))
            story.append(Spacer(1, 6))

        story.append(Spacer(1, 15))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()


@celery_app.task(bind=True, max_retries=2, default_retry_delay=5)
def generate_report_task(self, project_id: int, report_id: int, report_type: str, formats: list[str]):
    db = SyncSessionLocal()
    try:
        report = db.query(Report).filter(Report.id == report_id).first()
        if not report:
            return {"error": "Report not found"}

        report_content = {
            "executive_summary": {
                "title": "Executive Summary",
                "content": "Comprehensive startup intelligence analysis generated by AgentOps AI agents.",
            },
            "market_analysis": {
                "title": "Market Analysis",
                "content": [
                    "Total Addressable Market analysis conducted",
                    "Market growth trends and projections",
                    "Industry competitive landscape assessment",
                    "Target market segmentation identified",
                ],
            },
            "competitive_analysis": {
                "title": "Competitive Analysis",
                "content": [
                    "Direct and indirect competitor mapping",
                    "Market positioning analysis",
                    "Competitive advantage assessment",
                    "SWOT analysis completed",
                ],
            },
            "business_strategy": {
                "title": "Business Strategy",
                "content": "Revenue model, pricing strategy, and go-to-market plan developed by Business Strategy Agent.",
            },
            "investor_review": {
                "title": "Investor Review",
                "content": "Risk assessment, funding readiness evaluation, and VC recommendations provided.",
            },
            "pitch_recommendations": {
                "title": "Pitch Recommendations",
                "content": [
                    "Problem-Solution narrative framework",
                    "Market opportunity sizing",
                    "Business model presentation",
                    "Team and traction highlights",
                    "Investment ask and use of funds",
                ],
            },
        }
        report.content = report_content
        report.status = ReportStatus.COMPLETED
        report.completed_at = datetime.utcnow()

        if "pdf" in formats:
            pdf_bytes = _generate_pdf_content(report, db)
            report.file_path = f"/tmp/agentops/reports/{report_id}.pdf"
            import os
            os.makedirs(os.path.dirname(report.file_path), exist_ok=True)
            with open(report.file_path, "wb") as f:
                f.write(pdf_bytes)
            report.file_size_bytes = len(pdf_bytes)

        db.commit()

        return {
            "report_id": report_id,
            "project_id": project_id,
            "status": "completed",
            "format": formats,
        }

    except Exception as exc:
        db.rollback()
        report = db.query(Report).filter(Report.id == report_id).first()
        if report:
            report.status = ReportStatus.FAILED
            report.error_message = str(exc)
            db.commit()

        try:
            self.retry(exc=exc)
        except Exception:
            return {"error": str(exc), "report_id": report_id}

    finally:
        db.close()
